query GetAlbums {
  albums {
    _id
    number
    name
    year
    songIds
    songs {
      _id
      number
      name
    }
  }
}

query GetAlbum($albumId: ID!) {
  album(albumId: $albumId) {
    _id
    number
    name
    year
    songIds
    songs {
      _id
      number
      name
    }
  }
}

mutation DeleteAlbums {
  deleteAlbums {
    acknowledged
    deletedCount
  }
}

mutation CreateAlbum($createAlbumInput: CreateAlbumInput!) {
  createAlbum(input: $createAlbumInput) {
    _id
    number
    name
    year
    songs {
      _id
      number
      name
    }
  }
}

mutation UpdateAlbum($albumId: ID!, $updateAlbumInput: UpdateAlbumInput!) {
  updateAlbum(albumId: $albumId, input: $updateAlbumInput) {
    _id
    number
    name
    year
    songIds
    songs {
      _id
      number
      name
    }
  }
}

mutation AddSongsToAlbum($albumId: ID!, $songIds: [ID!]!) {
  addSongsToAlbum(albumId: $albumId, songIds: $songIds) {
    _id
    number
    name
    year
    songIds
    songs {
      _id
      number
      name
    }
  }
}

mutation DeleteAlbum($albumId: ID!) {
  deleteAlbum(albumId: $albumId) {
    acknowledged
    deletedCount
  }
}

