query GetSongs {
  songs {
    _id
    number
    name
  }
}

query GetSong($songId: ID!) {
  song(songId: $songId) {
    _id
    number
    name
  }
},

mutation DeleteSongs {
  deleteSongs {
    acknowledged
    deletedCount
  }
}

mutation CreateSong($createSongInput: CreateSongInput!) {
  createSong(input: $createSongInput) {
    _id
    number
    name
  }
}

mutation CreateSongError($createSongErrorInput: CreateSongInput!) {
  createSong(input: $createSongErrorInput) {
    _id
    number
    name
  }
}

mutation UpdateSong($songId: ID!, $updateSongInput: UpdateSongInput!) {
  updateSong(songId: $songId, input: $updateSongInput) {
    _id
    number
    name
  }
}

mutation DeleteSong($songId: ID!) {
  deleteSong(songId: $songId) {
    acknowledged
    deletedCount
  }
}
