query GetArtists {
  artists {
    _id
    name
    albumIds
    albums {
      _id
      number
      name
      year
      songs {
        _id
        number
        name
      }
    }
  }
}

query GetArtist($artistId: ID!) {
  artist(artistId: $artistId) {
    _id
    name
    albumIds
    albums {
      _id
      number
      name
      year
      songs {
        _id
        number
        name
      }
    }
  }
}

mutation DeleteArtists {
  deleteArtists {
    acknowledged
    deletedCount
  }
}

mutation CreateArtist($createArtistInput: CreateArtistInput!) {
  createArtist(input: $createArtistInput) {
    _id
    name
    albums {
      _id
      number
      name
      year
      songs {
        _id
        number
        name
      }
    }
  }
}

mutation UpdateArtist($artistId: ID!, $updateArtistInput: UpdateArtistInput!) {
  updateArtist(artistId: $artistId, input: $updateArtistInput) {
    _id
    name
    albumIds
    albums {
      _id
      number
      name
      year
      songs {
        _id
        number
        name
      }
    }
  }
}

mutation DeleteArtist($artistId: ID!) {
  deleteArtist(artistId: $artistId) {
    acknowledged
    deletedCount
  }
}

mutation AddAlbumsToArtist($artistId: ID!, $albumIds: [ID!]!) {
  addAlbumsToArtist(artistId: $artistId, albumIds: $albumIds) {
    _id
    name
    albumIds
    albums {
      _id
      number
      name
      year
      songs {
        _id
        number
        name
      }
    }
  }
}
